### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CodingSpiderFox** [proxmox/pve-cluster#6]
What license is to be applied for the source code in this repo?

Thank you

**Comment by keks24** [comment]
Have a look at this:
>If a repository has no license, then all rights are reserved and it is not Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder.
[...]
In short, the only thing you can safely assume is that you have no rights to do anything at all with this code. In the particular case of GitHub, you can fork the repository and view the code, but nothing more.

https://opensource.stackexchange.com/a/1721

**Comment by CodingSpiderFox** [comment]
OK, thanks for the clarification.
